function dYdt = Kugle_sys8(t,Y,th1,th1_d,th2,th2_d,th3,th3_d,g,m0,m1,m2,m3,l1,l2,l3)
%KUGLE_SYS8
%    DYDT = KUGLE_SYS8(T,Y,TH1,TH1_D,TH2,TH2_D,TH3,TH3_D,G,M0,M1,M2,M3,L1,L2,L3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-May-2019 11:55:52

dYdt = [Y(2);0.0];
