function dYdt = PendulumModel_sys(t,Y,th2,th2_d,th3,th3_d,g,m1,m2,m3,l1,l2,l3)
%PENDULUMMODEL_SYS
%    DYDT = PENDULUMMODEL_SYS(T,Y,TH2,TH2_D,TH3,TH3_D,G,M1,M2,M3,L1,L2,L3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-May-2019 11:52:40

t2 = Y(1);
t3 = t2+th2;
t4 = sin(t3);
t5 = sin(t2);
t6 = l1.^2;
t7 = l2.^2;
t8 = cos(th2);
dYdt = [Y(2);((g.*l1.*m1.*t5+g.*l1.*m2.*t5.*2.0+g.*l2.*m2.*t4+g.*l1.*m3.*t5.*2.0+g.*l2.*m3.*t4.*2.0+g.*l3.*m3.*sin(t2+th2+th3)).*(3.0./2.0))./(m1.*t6+m2.*t6.*3.0+m2.*t7+m3.*t6.*3.0+m3.*t7.*3.0+l3.^2.*m3+l1.*l2.*m2.*t8.*3.0+l1.*l2.*m3.*t8.*6.0+l1.*l3.*m3.*cos(th2+th3).*3.0+l2.*l3.*m3.*cos(th3).*3.0)];
